
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luuti
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private double num1 = 0, num2 = 0, result = 0;
    private char operator;

    public NewJFrame() {
        initComponents();
        addButtonListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setText("CASINO");

        jPanel2.setLayout(new java.awt.GridLayout(4, 5, 5, 5));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("2");
        jPanel2.add(jButton2);

        jButton3.setText("3");
        jPanel2.add(jButton3);

        jButton4.setText("/");
        jPanel2.add(jButton4);

        jButton5.setText("sqrt");
        jPanel2.add(jButton5);

        jButton6.setText("4");
        jPanel2.add(jButton6);

        jButton7.setText("5");
        jPanel2.add(jButton7);

        jButton8.setText("6");
        jPanel2.add(jButton8);

        jButton13.setText("*");
        jPanel2.add(jButton13);

        jButton9.setText("%");
        jPanel2.add(jButton9);

        jButton17.setText("7");
        jPanel2.add(jButton17);

        jButton10.setText("8");
        jPanel2.add(jButton10);

        jButton11.setText("9");
        jPanel2.add(jButton11);

        jButton12.setText("+");
        jPanel2.add(jButton12);

        jButton14.setText("1/x");
        jPanel2.add(jButton14);

        jButton15.setText("0");
        jPanel2.add(jButton15);

        jButton16.setText("jButton16");
        jPanel2.add(jButton16);

        jButton18.setText("C");
        jPanel2.add(jButton18);

        jButton19.setText("-");
        jPanel2.add(jButton19);

        jButton20.setText("=");
        jPanel2.add(jButton20);

        jTextField1.setText("xnxx");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addButtonListeners() {
        JButton[] numberButtons = { jButton1, jButton2, jButton3, jButton6, jButton7, jButton8, jButton17, jButton10, jButton11, jButton15 };
        for (JButton btn : numberButtons) {
            btn.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jTextField1.setText(jTextField1.getText() + btn.getText());
                }
            });
        }

        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setOperator('/');
            }
        });

        jButton13.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setOperator('*');
            }
        });

        jButton12.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setOperator('+');
            }
        });

        jButton19.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setOperator('-');
            }
        });

        jButton20.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                calculateResult();
            }
        });

        jButton18.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clear();
            }
        });

        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                performSpecialOperation("sqrt");
            }
        });

        jButton14.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                performSpecialOperation("1/x");
            }
        });

        jButton9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                performSpecialOperation("%");
            }
        });

        jButton16.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1.setText(jTextField1.getText() + ".");
            }
        });
    }

    private void setOperator(char op) {
        num1 = Double.parseDouble(jTextField1.getText());
        operator = op;
        jTextField1.setText("");
    }

    private void calculateResult() {
        num2 = Double.parseDouble(jTextField1.getText());
        switch (operator) {
            case '+': result = num1 + num2; break;
            case '-': result = num1 - num2; break;
            case '*': result = num1 * num2; break;
            case '/': result = num1 / num2; break;
            case '%': result = num1 % num2; break;
        }
        jTextField1.setText(String.valueOf(result));
        num1 = result;
    }

    private void clear() {
        jTextField1.setText("");
        num1 = num2 = result = 0;
        operator = '\0';
    }

    private void performSpecialOperation(String op) {
        double value = Double.parseDouble(jTextField1.getText());
        switch (op) {
            case "sqrt" -> value = Math.sqrt(value);
            case "1/x" -> value = 1 / value;
            case "%" -> value = value / 100;
        }
        jTextField1.setText(String.valueOf(value));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

  
}
