/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package n10th9;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Nhacungcap extends javax.swing.JFrame {

    /**
     * Creates new form Nhacungcap
     */
    public Nhacungcap() {
        initComponents();
        load_nhacc();
        load_cboNhacc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMancc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenncc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhacc = new javax.swing.JTable();
        cboNhacc = new javax.swing.JComboBox<>();
        txtKetqua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNhacc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chi tiết sản phẩm");

        jLabel2.setText("Mã sản phẩm");

        jLabel3.setText("Tên sản phẩm");

        jLabel4.setText("Giá");

        jLabel5.setText("Số lượng");

        jLabel6.setText("Tác vụ");

        jLabel7.setText("Nhập tên sách");

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lưu");

        jButton4.setText("Cập nhật");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Xoá");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbNhacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbNhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhaccMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhacc);

        cboNhacc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNhaccItemStateChanged(evt);
            }
        });
        cboNhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNhaccActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã nhà cc");

        jLabel9.setText("Mã ncc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMancc)
                                .addComponent(txtGia)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtNhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboNhacc, 0, 166, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTenncc)
                                        .addComponent(txtSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton5)))))))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboNhacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKetqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNhacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Connection con;
    Map<String,String> nhacc = new HashMap<>();
    private void load_cboNhacc(){
        try{
            con = connectDB.KetnoiDB();
            String sql = "Select * From Nhacungcapp";
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            //Đổ dữ liệu vào combobox
            while(rs.next()){
                cboNhacc.addItem(rs.getString("tenncc"));
                nhacc.put(rs.getString("tenncc"), rs.getString("mancc"));
            }
            con.close();;
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    private boolean Checktrungmanhacc(String mncc){
        boolean kq = false;
        try{
            Connection con = connectDB.KetnoiDB();
            String sql = "Select * From Sanpham Where masp='"+ mncc +"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(!rs.next()){
                kq=true;
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return kq;
    }
    
    private void load_nhacc(){
        try{
            tbNhacc.removeAll();
            Connection con = connectDB.KetnoiDB();
            //tao doi tuong statement de thuc hien lenh truy van
            String sql = "Select * From Sanpham";
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String[] tieude = {"Mã sản phẩm", "Tên sản phẩm","Giá","Số lượng","Mã nhà cc"};
            DefaultTableModel tb = new DefaultTableModel(tieude,0);
            while(rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("masp"));
                v.add(rs.getString("tensp"));
                v.add(rs.getString("gia"));
                v.add(rs.getString("soluong"));
                v.add(rs.getString("mancc"));
                tb.addRow(v);
            }
            tbNhacc.setModel(tb);
            con.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String mncc = txtMancc.getText().trim();
        if(mncc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập mã sp!");
            return;
        }
        String tncc = txtTenncc.getText().trim();
        if(tncc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập tên sp!");
            return;
        }
        
        String gia = txtGia.getText().trim();
        if(gia.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập giá!");
            return;
        }
        String regex_gia = "^\\d+(\\.\\d{1,2})?$";
        Pattern pat = Pattern.compile(regex_gia);
        Matcher  mat = pat.matcher(gia);
        if(!mat.matches()){
            JOptionPane.showMessageDialog(this, "Nhập sai giá !!");
            return;
        }
        
        String sl = txtSoluong.getText().trim();
        if(sl.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập số lượng!");
            return;
        }
        int soLuong = Integer.parseInt(sl);

        if(soLuong > 100){
    JOptionPane.showMessageDialog(this, "Số lượng không được vượt quá 100!");
    return;
}
        String regex_sl = "^\\d+$";
        Pattern patt = Pattern.compile(regex_sl);
        Matcher  matt = patt.matcher(sl);
        if(!mat.matches()){
            JOptionPane.showMessageDialog(this, "Nhập sai số lượng !!");
            return;
        }
        String ncc = txtNhacc.getText().trim();
        if(ncc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập nhà cc!");
            return;
        }
        if(!Checktrungmanhacc(mncc)){
            JOptionPane.showMessageDialog(this, "Trùng mã sp!");
            return;
        }
        
        try{
            Connection con = connectDB.KetnoiDB();
            String sql = "Insert Sanpham values('"+ mncc +"',N'" + tncc + "','" + gia + "','" + sl + "','" + ncc + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!"); 
            load_nhacc();
        }
        catch (Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbNhaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhaccMouseClicked
        // TODO add your handling code here:
        int i = tbNhacc.getSelectedRow();
        DefaultTableModel tb = (DefaultTableModel)tbNhacc.getModel();
        txtMancc.setText(tb.getValueAt(i, 0).toString());
        txtTenncc.setText(tb.getValueAt(i, 1).toString());
        txtGia.setText(tb.getValueAt(i, 2).toString());
        txtSoluong.setText(tb.getValueAt(i, 3).toString());
        txtNhacc.setText(tb.getValueAt(i, 4).toString());
        txtMancc.setEnabled(false);
        
    }//GEN-LAST:event_tbNhaccMouseClicked

    private void cboNhaccItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNhaccItemStateChanged
        // TODO add your handling code here:
        String tenncc = cboNhacc.getSelectedItem().toString();
        txtKetqua.setText(nhacc.get(tenncc));
    }//GEN-LAST:event_cboNhaccItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            String mtg = txtMancc.getText();
           if(mtg.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập mã sp!");
            return;
        }
            String ttg = txtTenncc.getText();
           if(ttg.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập tên sp!");
            return;
        }
           
            String dt = txtGia.getText();
          if(dt.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập giá!");
            return;
        }
        String regex_gia = "^\\d+(\\.\\d{1,2})?$";
        Pattern pat = Pattern.compile(regex_gia);
        Matcher  mat = pat.matcher(dt);
        if(!mat.matches()){
            JOptionPane.showMessageDialog(this, "Nhập sai giá !!");
            return;
        }
            String email = txtSoluong.getText();
            if(email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập số lượng!");
            return;
        }
        int soLuong = Integer.parseInt(email);

        if(soLuong > 100){
    JOptionPane.showMessageDialog(this, "Số lượng không được vượt quá 100!");
    return;
}
        String regex_sl = "^\\d+$";
        Pattern patt = Pattern.compile(regex_sl);
        Matcher  matt = patt.matcher(email);
        if(!mat.matches()){
            JOptionPane.showMessageDialog(this, "Nhập sai số lượng !!");
            return;
        }
            String ncc = txtNhacc.getText();
            if(ncc.isEmpty()){
            JOptionPane.showMessageDialog(this, "Phải nhập nhà cc!");
            return;
        }
            Connection con = connectDB.KetnoiDB();
            String sql = "Update Sanpham Set tensp=N'"+ttg+"',gia='"+dt+"',"
                    + "soluong='"+email+"',"
            + "mancc=N'"+ncc+"' Where masp='"+mtg+"'";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            load_nhacc();
        }catch (Exception ex){
            ex.printStackTrace();
        }
    
                                              
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
        String mtg = txtMancc.getText();
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá không?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            Connection con = connectDB.KetnoiDB();
            String sql = "Delete From Sanpham Where masp='"+mtg+"'";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Xoá thành công");
            load_nhacc();
        } else {
            JOptionPane.showMessageDialog(this, "Không xoá nữa thì thôi");
        }
    }catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                try{
            //lấy dữ liệu từ compoment đưa vài biến
            String mtg = txtMancc.getText().trim();
            String ttg = txtTenncc.getText().trim();
            String sl = txtSoluong.getText().trim();
            Connection con = connectDB.KetnoiDB();
            String sql = "Select * From Sanpham Where masp like'%"+mtg+"%' and tensp like N'%"+ttg+"%' and soluong like N'%"+sl+"%'";
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String[] tieude = {"Mã sản phẩm", "Tên sản phẩm","Giá","Số lượng","Mã nhà cc"};
            DefaultTableModel tb = new DefaultTableModel(tieude,0);
            while(rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("masp"));
                v.add(rs.getString("tensp"));
                v.add(rs.getString("gia"));
                v.add(rs.getString("soluong"));
                v.add(rs.getString("mancc"));
                tb.addRow(v);
            }
            tbNhacc.setModel(tb);
            con.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboNhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNhaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNhaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhacungcap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhacungcap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhacungcap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhacungcap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhacungcap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNhacc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNhacc;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtKetqua;
    private javax.swing.JTextField txtMancc;
    private javax.swing.JTextField txtNhacc;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenncc;
    // End of variables declaration//GEN-END:variables
}
