/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package n10th9;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;
/**
 *
 * @author Acer
 */
public class tacgia extends javax.swing.JFrame {

    /**
     * Creates new form tacgia
     */
    public tacgia() {
        initComponents();
        load_tacgia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tacgia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        bt_luu = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        bt_thoat = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        chongioitinh = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        matacgia = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        dienthoai = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        diachi = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        email = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        hovaten = new javax.swing.JTextPane();
        Xuat_Excel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã tác giả", "Họ và tên", "Ngày sinh", "Giới tính", "Điện thoại", "Email", "Địa chỉ"
            }
        ));
        tacgia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tacgiaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tacgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tacgia);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Cập nhật thông tin tác giả");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã tác giả:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Điện thoại: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giới tính: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ: ");

        bt_luu.setBackground(new java.awt.Color(204, 255, 255));
        bt_luu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_luu.setText("Lưu");
        bt_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luuActionPerformed(evt);
            }
        });

        bt_sua.setBackground(new java.awt.Color(255, 204, 204));
        bt_sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_sua.setText("Sửa");
        bt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaActionPerformed(evt);
            }
        });

        bt_thoat.setBackground(new java.awt.Color(153, 255, 204));
        bt_thoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_thoat.setForeground(new java.awt.Color(51, 0, 255));
        bt_thoat.setText("Thoát");
        bt_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thoatActionPerformed(evt);
            }
        });

        bt_xoa.setBackground(new java.awt.Color(255, 102, 102));
        bt_xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_xoa.setText("Xóa");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        chongioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chon gioi tinh", "Nam ", "Nữ", "khac" }));
        chongioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chongioitinhActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(matacgia);

        jScrollPane3.setViewportView(dienthoai);

        jScrollPane4.setViewportView(diachi);

        jScrollPane5.setViewportView(email);

        jScrollPane6.setViewportView(hovaten);

        Xuat_Excel.setBackground(new java.awt.Color(204, 255, 255));
        Xuat_Excel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Xuat_Excel.setText("Xuất Excel");
        Xuat_Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xuat_ExcelActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("tim kiem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(bt_luu)
                                .addGap(18, 18, 18)
                                .addComponent(bt_sua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_xoa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chongioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Xuat_Excel)
                        .addGap(117, 117, 117)
                        .addComponent(jButton2)
                        .addGap(279, 279, 279)
                        .addComponent(bt_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chongioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_sua)
                            .addComponent(bt_xoa)
                            .addComponent(Xuat_Excel)
                            .addComponent(bt_luu)
                            .addComponent(jButton2))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_thoat)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luuActionPerformed

        String mtg = matacgia.getText().trim();
        String ht = hovaten.getText().trim();
        Date ns = new Date(ngaysinh.getDate().getTime());
        String gt = chongioitinh.getSelectedItem().toString();
        String dt = dienthoai.getText().trim();
        String em = email.getText().trim();
        String dc = diachi.getText().trim();
        try {
            Connection con = connectDB.KetnoiDB();
            String sql = "INSERT Tacgia Values('" + mtg + "',N'" + ht + "','" + ns + "',N'" + gt + "','" + dt + "','" + em + "', N'" + dc + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
            load_tacgia();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_luuActionPerformed

    private void load_tacgia() {
        try {
            Connection con;
            con = connectDB.KetnoiDB();
            Statement st = con.createStatement();
            String sql = "Select * From Tacgia ORDER BY Matacgia ASC";
            ResultSet rs = st.executeQuery(sql);
            //   tbLoaiSach.removeAll();
            String[] arr = {"Mã tác giả", "Họ tên", "Ngày sinh", "Giới tính", "Điện thoại", "Email", "Địa chỉ"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("Matacgia"));
                v.add(rs.getString("Hoten"));
                v.add(rs.getString("Ngaysinh"));
                v.add(rs.getString("Gioitinh"));
                v.add(rs.getString("Dienthoai"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Diachi"));
                model.addRow(v);
            }
            tacgia.setModel(model);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void bt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaActionPerformed
        String mtg = matacgia.getText().trim();
        String ht = hovaten.getText().trim();
        Date ns = new Date(ngaysinh.getDate().getTime());
        String gt = chongioitinh.getSelectedItem().toString();
        String dt = dienthoai.getText().trim();
        String em = email.getText().trim();
        String dc = diachi.getText().trim();
        try {
            Connection con = connectDB.KetnoiDB();
            String sql = "Update Tacgia Set Hoten=N'" + ht + "',Ngaysinh=N'" + ns + "',Gioitinh=N'" + gt + "',Dienthoai=N'" + dt + "',Email=N'" + em + "',Diachi=N'" + dc + "' where Matacgia='" + mtg + "' ";
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            load_tacgia();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bt_suaActionPerformed

    private void bt_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_thoatActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        try {
            String mtg = matacgia.getText().trim();
            Connection con = connectDB.KetnoiDB();
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                String sql = "Delete from tacgia where Matacgia='" + mtg + "' ";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                con.close();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                load_tacgia();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_xoaActionPerformed

    private void tacgiaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tacgiaAncestorAdded

    }//GEN-LAST:event_tacgiaAncestorAdded

    private void tacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacgiaMouseClicked
        int i = tacgia.getSelectedRow();
        DefaultTableModel tb = (DefaultTableModel) tacgia.getModel();
        matacgia.setText(tb.getValueAt(i, 0).toString());
        hovaten.setText(tb.getValueAt(i, 1).toString());
        String ngay = tb.getValueAt(i, 2).toString();
        java.util.Date ns;
        try {
            ns = new SimpleDateFormat("yyyy-MM-dd").parse(ngay);
            ngaysinh.setDate(ns);
        } catch (Exception e) {
            e.printStackTrace();
        }
        chongioitinh.setSelectedItem(tb.getValueAt(i, 3).toString());
        dienthoai.setText(tb.getValueAt(i, 4).toString());
        email.setText(tb.getValueAt(i, 5).toString());
        diachi.setText(tb.getValueAt(i, 6).toString());
        matacgia.setEnabled(false);
    }//GEN-LAST:event_tacgiaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        matacgia.setEnabled(true);
        matacgia.setText("");
        hovaten.setText("");
        dienthoai.setText("");
        ngaysinh.setDate(null);
        email.setText("");
        diachi.setText("");
        chongioitinh.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Xuat_ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xuat_ExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Xuat_ExcelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String mtg = matacgia.getText().trim();
            String ht = hovaten.getText().trim();
            String gt = chongioitinh.getSelectedItem().toString();

            if (gt.equals("chon gioi tinh")) {
                gt = "";
            }

            Connection con = connectDB.KetnoiDB();
            String sql = "SELECT * FROM Tacgia WHERE Matacgia LIKE '%" + mtg + "%' AND Hoten LIKE N'%" + ht + "%'AND Gioitinh LIKE N'%" + gt + "%'";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            // Bảng tiêu đề
            String[] arr = {"Mã tác giả", "Họ tên", "Ngày sinh", "Giới tính", "Điện thoại", "Email", "Địa chỉ"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("Matacgia"));
                v.add(rs.getString("Hoten"));
                v.add(rs.getString("Ngaysinh"));
                v.add(rs.getString("Gioitinh"));
                v.add(rs.getString("Dienthoai"));
                v.add(rs.getString("Email"));
                v.add(rs.getString("Diachi"));
                model.addRow(v);
            }

            tacgia.setModel(model);
            con.close();

        } catch (Exception e) {
            e.printStackTrace();  // In lỗi ra console
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chongioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chongioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chongioitinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tacgia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Xuat_Excel;
    private javax.swing.JButton bt_luu;
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_thoat;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JComboBox<String> chongioitinh;
    private javax.swing.JTextPane diachi;
    private javax.swing.JTextPane dienthoai;
    private javax.swing.JTextPane email;
    private javax.swing.JTextPane hovaten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane matacgia;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private javax.swing.JTable tacgia;
    // End of variables declaration//GEN-END:variables
}
